fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    win_env: "git://github.com/voxpupuli/puppet-windows_env.git"
    registry: "git://github.com/puppetlabs/puppetlabs-registry.git"
    powershell:  git://github.com/puppetlabs/puppetlabs-powershell.git
    win_facts:  git://github.com/liamjbennett/puppet-win_facts.git
  symlinks:
    chrome: "#{source_dir}"
